# Dockerfile.frontend
FROM node:16

# Répertoire de travail
WORKDIR /usr/src/app

# Copier les fichiers de gestion de dépendances et installer
COPY package*.json ./
RUN npm install

# Copier tout le code de l’app
COPY . .

# Exposer le port Angular
EXPOSE 4200

# Lancer le serveur de dev Angular
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]
